server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit-properties:
  queue: q.testQueue
  routingKey: r.testRoutingKey
  exchange: e.testExchange
